#     ___   ______
#    /   | / ____/ 
#   / /| |/ /      By jonagamerpro1234
#  / ___ / /___    Version 1.7.x - 1.8.x
# /_/  |_\____/    Thanks for using AdvancedChat <3
#  
# ● a simple plugin that helps you customize your server chat to make it look better also provides a customizable chat system by group or rank
#  
# ● Spigot: https://www.spigotmc.org/resources/advancedchat-1-7-x-1-17-x.83889/
# ● Songoda: https://songoda.com/marketplace/product/advancedchat-chat-related.542
# ● Wiki [Working Progress]: https://jonagamerpro1234.gitbook.io/advancedchat/
# ● Discord: https://discord.gg/c5GhQDQCK5
# ● Issue Tracker: https://github.com/jonagamerpro1234/AdvancedChat/issues
# ● Bstast: https://bstats.org/plugin/bukkit/AdvancedChat/8826
#
# |Default-Channel|
# Types: [ALL] [Local] [Group] comming soon more options
Default-Channel: ALL
#
# |DataBase|
DataBase:
  Host: 'localhost'
  port: '3306'
  database: 'advancedchatDB'
  username: 'root'
  password: '1234'
#
# |Translation of messages from AdvancedChat|
# |Version: 1.7.x - 1.8.x|
#
AdvancedChat:
  Error-Sync-DataBase: ''
  No-Permission: '&cYou dont have permission to do that!'
  No-Permission-Label: 'Ask the server owner or an administrator for help for more information.'
  Error-Args: '&cUnknown Arguments'
  Reload: '&aReload Completed'
  Help-Mute: '&7Use &b/Mute &e<player> &7'
  Help-UnMute: '&7Use &b/UnMute &e<player> &7'
  Help-Cmd: '&7Use &b/AdvanceChat &8| &9/Ac &6Help &7 show more information of plugin'
#
# This is the end of the configuration ... [-_-] more things coming soon
# 
# | Config File
# | Version 1.7.x - 1.8.x
#