name: AdvancedChat
version: '${project.version}'
main: jss.advancedchat.AdvancedChat
api-version: 1.13
softdepend: [
  PlaceholderAPI, ProtocolLib
]
website: https://github.com/jonagamerpro1234/AdvancedChat/

commands:
  AdvancedChat:
    description: main command
    aliases:
      - ac
  AdClearChat:
    description: ---
    aliases:
      - cc
      - clearchat
  AdMute:
    description: ---
    aliases:
      - mute
  AdUnMute:
    description: ---
    aliases:
      - unmute