package jss.advancedchat.utils;

public class Perms {
	
	public static String ac_ = "advancedchat.";
	public static String ac_update = "advancedchat.update";
	public static String ac_all = "advancedchat.admin";
	public static String ac_colors_all = "advancedchat.colors.all";
	public static String ac_cmd_reload = "advancedchat.command.reload";
	public static String ac_cmd_help = "advancedchat.command.help";
	public static String ac_cmd_color = "advancedchat.command.color";
	public static String ac_cmd_gradient = "advancedchat.command.gradient";
	public static String ac_cmd_player = "advancedchat.command.player";
	public static String ac_cmd_settings = "advancedchat.command.settings";
	public static String ac_cmd_info = "advancedchat.command.info";
	public static String ac_cmd_clearchat = "advancedchat.command.clearchat";
	public static String ac_clearchat_bypass = "advancedchat.clearchat.bypass";
	public static String ac_cmd_mute = "advancedchat.command.mute";
	public static String ac_cmd_unmute = "advancedchat.command.unmute";
	public static String ac_cmd_tabcomplete = "advancedchat.tabcomplete";
	public static String ac_mute_bypass = "advancedchat.mute.bypass";
	public static String ac_gui_ = "advancedchat.gui.";
	public static String ac_gui_colors = "advancedchat.gui.colors";
	public static String ac_gui_specialcolorcodes = "advancedchat.gui.specialcolocodes";
	public static String ac_gui_colors_red = "advancedchat.gui.colors.red";
	public static String ac_gui_colors_darkred = "advancedchat.gui.colors.darkred";
	public static String ac_gui_colors_blue = "advancedchat.gui.colors.blue";
	public static String ac_gui_colors_darkblue = "advancedchat.gui.colors.darkblue";
	public static String ac_gui_colors_green = "advancedchat.gui.colors.green";
	public static String ac_gui_colors_darkgreen = "advancedchat.gui.colors.darkgreen";
	public static String ac_gui_colors_yellow = "advancedchat.gui.colors.yellow";
	public static String ac_gui_colors_gold = "advancedchat.gui.colors.gold";
	public static String ac_gui_colors_aqua = "advancedchat.gui.colors.aqua";
	public static String ac_gui_colors_darkaqua = "advancedchat.gui.colors.darkaqua";
	public static String ac_gui_colors_lightpurple = "advancedchat.gui.colors.lightpurple";
	public static String ac_gui_colors_darkpurple = "advancedchat.gui.colors.darkpurple";
	public static String ac_gui_colors_gray = "advancedchat.gui.colors.gray";
	public static String ac_gui_colors_darkgray = "advancedchat.gui.colors.darkgray";
	public static String ac_gui_colors_white = "advancedchat.gui.colors.white";
	public static String ac_gui_colors_black = "advancedchat.gui.colors.black";
	public static String ac_gui_colors_random = "advancedchat.gui.colors.random";
	public static String ac_gui_player = "advancedchat.gui.player";
	public static String ac_gui_player_mute = "advancedchat.gui.player.mute";
	public static String ac_gui_gradient = "advancedchat.gui.gradient";
	public static String ac_gui_gradient_red = "advancedchat.gui.gradient.red";
	public static String ac_gui_gradient_darkred = "advancedchat.gui.gradient.darkred";
	public static String ac_gui_gradient_blue = "advancedchat.gui.gradient.blue";
	public static String ac_gui_gradient_darkblue = "advancedchat.gui.gradient.darkblue";
	public static String ac_gui_gradient_green = "advancedchat.gui.gradient.green";
	public static String ac_gui_gradient_darkgreen = "advancedchat.gui.gradient.darkgreen";
	public static String ac_gui_gradient_yellow = "advancedchat.gui.gradient.yellow";
	public static String ac_gui_gradient_gold = "advancedchat.gui.gradient.gold";
	public static String ac_gui_gradient_aqua = "advancedchat.gui.gradient.aqua";
	public static String ac_gui_gradient_darkaqua = "advancedchat.gui.gradient.darkaqua";
	public static String ac_gui_gradient_lightpurple = "advancedchat.gui.gradient.lightpurple";
	public static String ac_gui_gradient_darkpurple = "advancedchat.gui.gradient.darkpurple";
	public static String ac_gui_gradient_gray = "advancedchat.gui.gradient.gray";
	public static String ac_gui_gradient_darkgray = "advancedchat.gui.gradient.darkgray";
	public static String ac_gui_gradient_white = "advancedchat.gui.gradient.white";
	public static String ac_gui_gradient_black = "advancedchat.gui.gradient.black";
	public static String ac_gui_settings = "advancedchat.gui.settings";
	public static String ac_gui_settings_lowmode = "advancedchat.gui.settings.lowmode";
	public static String ac_gui_settings_chat = "advancedchat.gui.settings.chat";
	public static String ac_gui_settings_mention = "advancedchat.gui.settings.mention";
	public static String ac_gui_settings_msg = "advancedchat.gui.settings.msg";
	public static String ac_gui_rainbow = "advancedchat.gui.rainbow";
	public static String ac_gui_rainbow_1 = "advancedchat.gui.rainbow.1";
	public static String ac_gui_rainbow_2 = "advancedchat.gui.rainbow.2";
	public static String ac_gui_rainbow_3 = "advancedchat.gui.rainbow.3";
	public static String ac_gui_rainbow_4 = "advancedchat.gui.rainbow.4";
	public static String ac_gui_rainbow_5 = "advancedchat.gui.rainbow.5";
	public static String ac_gui_rainbow_6 = "advancedchat.gui.rainbow.6";
	public static String ac_gui_rainbow_7 = "advancedchat.gui.rainbow.7";
	public static String ac_gui_rainbow_8 = "advancedchat.gui.rainbow.8";
	public static String ac_chat_bypass = "advancedchat.chat.bypass";
	public static String ac_chat_color = "advancedchat.chat.color";
	public static String ac_chat_magic = "advancedchat.chat.magic";
	public static String ac_chat_bold = "advancedchat.chat.bold";
	public static String ac_chat_striketherough = "advancedchat.chat.striketherough";
	public static String ac_chat_underline = "advancedchat.chat.underline";
	public static String ac_chat_italic = "advancedchat.chat.italic";
	
	
	
}
